vars:
  - src/conf/params.yaml

stages:
  collect_train:
    cmd: python src/data/collector.py src/conf/params.yaml train
    params:
      - src/conf/params.yaml:
        - data_collector_config.video_id_train
        - data_collector_config.n_batches
    deps:
      - src/data/collector.py
    outs:
      - ${train_data_paths.raw_data_path.chat_csv}
      - ${train_data_paths.raw_data_path.clips_csv}

  collect_test:
    cmd: python src/data/collector.py src/conf/params.yaml test
    params:
      - src/conf/params.yaml:
        - data_collector_config.video_id_test
        - data_collector_config.n_batches
    deps:
      - src/data/collector.py
    outs:
      - ${test_data_paths.raw_data_path.chat_csv}
      - ${test_data_paths.raw_data_path.clips_csv}

  process_train:
    cmd: python src/features/process.py src/conf/params.yaml train
    params:
      - src/conf/params.yaml:
        - processing_config.paste_min_words
        - processing_config.window_size
    deps:
      - src/features/process.py
      - ${train_data_paths.raw_data_path.chat_csv}
    outs:
      - ${train_data_paths.processed_data_path.chat_csv}

  process_test:
    cmd: python src/features/process.py src/conf/params.yaml test
    params:
      - src/conf/params.yaml:
        - processing_config.paste_min_words
        - processing_config.window_size
    deps:
      - src/features/process.py
      - ${test_data_paths.raw_data_path.chat_csv}
    outs:
      - ${test_data_paths.processed_data_path.chat_csv}

  resample_train:
    cmd: python src/features/resample.py src/conf/params.yaml train
    params:
      - src/conf/params.yaml:
        - undersample_config.random_state
    deps:
      - src/features/resample.py 
      - ${train_data_paths.processed_data_path.chat_csv}
      - ${train_data_paths.raw_data_path.clips_csv}
    outs:
      - ${train_data_paths.resampled_data_path.chat_csv}

  resample_test:
    cmd: python src/features/resample.py src/conf/params.yaml test
    deps:
      - src/features/resample.py
      - ${test_data_paths.processed_data_path.chat_csv}
      - ${test_data_paths.raw_data_path.clips_csv}
    outs:
      - ${test_data_paths.resampled_data_path.chat_csv}

  train:
    cmd: python src/models/train.py -m
    params:
      - src/conf/models/log_reg.yaml:
      - src/conf/models/rf_clf.yaml:
      - src/conf/models/xgb_clf.yaml:
      - src/conf/search_spaces/log_reg.yaml:
      - src/conf/search_spaces/rf_clf.yaml:
      - src/conf/search_spaces/xgb_clf.yaml:
    deps:
      - ${train_data_paths.resampled_data_path.chat_csv}
      - ${test_data_paths.resampled_data_path.chat_csv}

  register:
    cmd: python src/models/register.py
