train_data_paths:
  raw_data_path: 
    chat_csv: data/raw/chat_train.csv
    clips_csv: data/raw/clips_train.csv
  processed_data_path: 
    chat_csv: data/processed/chat_train.csv
    clips_csv: data/processed/clips_train.csv
  resampled_data_path: 
    chat_csv: data/resampled/chat_train.csv
    clips_csv: data/resampled/clips_train.csv

test_data_paths:
  raw_data_path: 
    chat_csv: data/raw/chat_test.csv
    clips_csv: data/raw/clips_test.csv
  processed_data_path: 
    chat_csv: data/processed/chat_test.csv
    clips_csv: data/processed/clips_test.csv
  resampled_data_path: 
    chat_csv: data/resampled/chat_test.csv
    clips_csv: data/resampled/clips_test.csv

data_collector_config:
  # video_id_train: '1990227660' # Melharucos'es VotV gameplay
  video_id_train: '2039157631' # UselessMouth Anime Stream 21.01.2024
  video_id_test: '2036131985' # UselessMouth Lethal Company Stream 18.01.2024
  # video_id_train: '1996646721' # Winline Media Poker Day 1
  # video_id_test: '1998428113' # Winline Media Poker Day 3
  n_batches: 32

processing_config:
  paste_min_words: 3
  window_size: 5

undersample_config:
  random_state: 42

target: highlight
actualize_config:
  enable: False
  max_zeros: 2
models:
- name: LogisticRegression
- name: RandomForestClassifier
  params: 
    max_depth: 7
    n_estimators: 400
- name: XGBClassifier
  params:
    max_depth: 9
    n_estimators: 400
    objective: binary:logistic
    eval_metric: auc
  
mlflow_config:
  remote_server_uri: http://localhost:5000