defaults:
  - _self_
  - params
  - models: xgb_clf
  - search_spaces@hydra.sweeper.params: ${models}
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: grid

hydra:
  sweeper:
    direction: maximize
    study_name: model
    storage: null
    n_trials: 20
    n_jobs: 4

optimized_metric: f1