defaults:
  - _self_
  - params
  - models: rf_clf
  - search_spaces@hydra.sweeper.params: ${models}
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
    direction: maximize
    study_name: model
    storage: null
    n_trials: 20
    n_jobs: 4

optimized_metric: f1